FROM golang:1.26-alpine AS dev
WORKDIR /app

RUN apk add --no-cache git
ENV PATH="/go/bin:$PATH"

COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/cosmtrek/air@v1.40.0

COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
